# Copyright 2026 The meq_jax Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for shapmex_lib.shap against the Octave shapmex implementation.

Conventions:

* MATLAB stores contours as ``rq``/``zq`` of shape (noq, npq) with one contour
  per column, the last column being the LCFS. The JAX implementation expects
  the transposed, row-major (npq, noq) layout, so we pass ``rq.T``/``zq.T``.

* The compiled mex accepts empty ``rB``/``zB`` (meaning "no boundary point");
  ``meq/shapmex.m`` documents this, and the C implementation maps empty
  inputs to the invalid value -1. Since majic/JAX does not support empty
  arrays, the JAX implementation uses the same convention: any ``rB < 0``
  disables the boundary-point replacement. This is covered by the
  ``no_boundary`` test variants below.

Realistic inputs are generated by running an fbt('ana', ...) equilibrium in
Octave and tracing flux-surface contours with find_contours (the same inputs
fsgi.m feeds to shapmex).
"""

from absl.testing import absltest
from absl.testing import parameterized
import jax
from meq_jax._src import shapmex_lib
from meqpy import octave_utils
import numpy as np

# Turn on float64 for comparison with Matlab implementation
jax.config.update('jax_enable_x64', True)

# pylint: disable=invalid-name


# Realistic flux surface contours from an analytic equilibrium, traced from
# the magnetic axis exactly as meqpostq/fsgi do. The last flux value is
# exactly FB, so the last contour is the LCFS and exercises the rB/zB
# boundary-point replacement branch.
_FIELDS_CMD = """
[L,~,LY] = fbt('ana', {shot}, 0, 'iterq', 50, 'noq', 64, 'icsint', false, 'ilim', 1);
fq = linspace(0.95, 0, 24);
F = LY.FB - fq*(LY.FB - LY.FA);
aq0 = 0.2*ones(L.noq, numel(F));
[rq, zq, ~] = find_contours(L, LY, F, aq0, LY.rA, LY.zA, L.crq, L.czq, LY.FA, int8(1));

rA = LY.rA; zA = LY.zA;
rB = LY.rB; zB = LY.zB;
dr2FA = LY.dr2FA; dz2FA = LY.dz2FA;
"""

_OUTPUT_NAMES = (
    'rgeom', 'zgeom', 'aminor', 'epsilon', 'kappa', 'delta', 'deltl',
    'deltu', 'rrmax', 'zrmax', 'rrmin', 'zrmin', 'rzmax', 'zzmax', 'rzmin',
    'zzmin',
)

_SHAPMEX_CMD = """
[rgeom,zgeom,aminor,epsilon,kappa,delta,deltl,deltu,...
 rrmax,zrmax,rrmin,zrmin,rzmax,zzmax,rzmin,zzmin] = shapmex(rq,zq,{rB},{zB},rA,zA,dr2FA,dz2FA);
"""


class ShapmexTest(parameterized.TestCase):

  @classmethod
  def setUpClass(cls):
    super().setUpClass()
    cls._oct = octave_utils.create_meq_oct2py_instance()

  @parameterized.named_parameters(
      ('limiter', 1, True),
      ('single_null', 2, True),
      ('elongated', 11, True),
      ('limiter_no_boundary', 1, False),
      ('single_null_no_boundary', 2, False),
      ('elongated_no_boundary', 11, False),
  )
  def test_shap_vs_matlab(self, shot, with_boundary):
    self._oct.eval(_FIELDS_CMD.format(shot=shot))

    rq = self._oct.eval('rq;', nout=1)  # (noq, npq)
    zq = self._oct.eval('zq;', nout=1)
    rA = self._oct.eval('rA;', nout=1)[0, 0]
    zA = self._oct.eval('zA;', nout=1)[0, 0]
    dr2FA = self._oct.eval('dr2FA;', nout=1)[0, 0]
    dz2FA = self._oct.eval('dz2FA;', nout=1)[0, 0]

    if with_boundary:
      rB = self._oct.eval('rB;', nout=1)[0, 0]
      zB = self._oct.eval('zB;', nout=1)[0, 0]
      cmd = _SHAPMEX_CMD.format(rB='rB', zB='zB')
    else:
      # Empty rB/zB in Matlab maps to the invalid value -1 inside the mex;
      # the JAX implementation uses the same "rB < 0 means no boundary point"
      # convention (see module docstring of shapmex_lib.py).
      rB = -1.0
      zB = -1.0
      cmd = _SHAPMEX_CMD.format(rB='[]', zB='[]')

    res_jax = jax.jit(shapmex_lib.shap)(
        rq=rq.T,  # JAX expects row-major (npq, noq)
        zq=zq.T,
        rB=rB,
        zB=zB,
        rA=rA,
        zA=zA,
        dr2fa=dr2FA,
        dz2fa=dz2FA,
    )

    res_matlab = self._oct.eval(cmd, nout=16)

    self.assertLen(res_jax, 16)
    for name, val_jax, val_matlab in zip(_OUTPUT_NAMES, res_jax, res_matlab):
      with self.subTest(name=name):
        val_jax = np.asarray(val_jax)
        val_matlab = np.asarray(val_matlab).squeeze()
        self.assertEqual(val_jax.shape, val_matlab.shape)
        # The C circle fit picks its pair of linear equations depending on
        # which coordinates coincide, while the JAX version always uses the
        # same pair; the solutions agree analytically but differ in the last
        # floating point ulps (observed max abs diff ~4e-15), so bitwise
        # agreement cannot be expected.
        np.testing.assert_allclose(val_jax, val_matlab, rtol=1e-12, atol=1e-13)


if __name__ == '__main__':
  absltest.main()

# pylint: enable=invalid-name
